---
- name: Install https for apt (Debian)
  apt: name=apt-transport-https state=present
  become: yes

- name: Get Icinga2 Apt Key for Debian OS family
  apt_key:
    id: C6E319C334410682
    url: "{{ icinga2_key }}"
    state: present
  become: yes

  # Debmon has been shut down and is not required any more
- name: Remove Debmon Apt Key for Debian OS family (Debian)
  apt_key:
    id: DC0EE15A29D662D2
    state: absent
  become: yes

- name: Get Icinga2 Apt Repos for Debian OS family
  apt_repository: repo='{{ item.repo }}'
                  update_cache=yes
                  state=present
  with_items: "{{ icinga2_deb_repos }}"
  become: yes

  # Debmon has been shut down and is not required any more
- name: Remove Debmon Apt Repo for Debian OS family (Debian)
  apt_repository: repo='{{ icinga2_debmon_repo }}'
                  update_cache=yes
                  state=absent
  become: yes

# Check if Icinga is installed
- stat:
      path: /usr/sbin/icinga2
  register: icinga2_file_stat
  become: yes

- name: Unhold Icinga packages
  dpkg_selections:
      name: "{{ item }}"
      selection: install
  with_items: "{{ icinga2_pkg }}"
  when: icinga2_file_stat.stat.exists == True
  become: yes

- name: Install Icinga2 on Debian OS family
  apt: name="{{ item }}={{ icinga2_debian_version }}.{{ ansible_distribution_release }}"
       update_cache=yes
       install_recommends=no
  with_items: "{{ icinga2_pkg }}"
  become: yes

- name: Set Icinga packges on hold
  dpkg_selections:
      name: "{{ item }}"
      selection: hold
  with_items: "{{ icinga2_pkg }}"
  become: yes

- name: Install monitoring plugins
  apt: name={{ item }}
       install_recommends=no
  with_items: "{{ icinga2_monitoring_plugins }}"

- name: Copy check_linux_memory
  copy:
      src: "check_linux_memory"
      dest: "/usr/lib/nagios/plugins"
      group: root
      owner: root
      mode: 0755
  become: yes

