---
# tasks file for ansible-icinga2-daemon

- include_tasks: icinga2_Debian_install.yml
  when: (ansible_os_family == "Debian" and ansible_distribution_major_version|int <= 8) or (ansible_distribution == "Ubuntu")

- include_tasks: icinga2_Debian_stretch_install.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 9

- include_tasks: icinga2_RedHat_install.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: icinga2_ticket.yml
  when: icinga2_ticket is not defined and icinga2_api_gen_ticket is defined
  tags:
    - icinga2_configure

- import_tasks: icinga2_configure.yml
  tags:
    - icinga2_configure